### ISSUE TITLE
这个只能用来捡漏吗。抢票可以吗？

### ISSUE THREAD

**Issue by zjtggssg** [lktlktlkt/pick-ticket-damai#2]
你好，想问一下软件是否可以用来抢票？

**Comment by lktlktlkt** [comment]
`ApiFetchPerform`这个类调度器准时接口抢票，可以根据配置更改快速请求次数(太频繁有验证码)。damai.init，damai.configs.default_configs有注释

**Comment by zjtggssg** [comment]
感谢，针对目前很多只能app购票也有效吗

**Comment by lktlktlkt** [comment]
只能h5

**Comment by zjtggssg** [comment]
也就是对于很多限定于app的大热门无效是吗，好的，感谢

**Comment by lktlktlkt** [comment]
嗯嗯，我感觉主要还是场地问题，有的热门的也支持h5
