### ISSUE TITLE
Cookie

### ISSUE THREAD

**Issue by 1802211205** [lktlktlkt/pick-ticket-damai#3]
要求cookie怎么获取，我获取到的cookie可能有点问题。
sku = next(sku for sku in sku_list if price == sku["priceName"])
StopIteration
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x0000024F076885B0>

**Comment by lktlktlkt** [comment]
浏览器登录后network中获取，你这个是配置中`PRICE`填写错误。目前没有实现用整数填写，需要完全复制价格项。

**Comment by 1802211205** [comment]
好的，还有请教一下在上个版本中，我购买票数2，在付款界面只自动勾选了第二个购票人，而第一个一直未勾选，是不是因为CRITICAL_WAIT设置的太小了

**Comment by lktlktlkt** [comment]
也有可能，和你的网络，设备配置有关，可以尝试调大测试一下。还有就是在浏览器设置中比例调成50%会好点，后面网页更新了，勾选不到
